// mockData.js
export const mockData = {
    events: [
        {
            id: 1,
            date: '2024-11-04',
            time: '13:00',
            title: 'Q4 성과 리뷰',
            important: false,
            content: '2024년도 4분기 실적 및 성과 리뷰 미팅\n참석 대상: 전체 팀장\n준비사항: 팀별 성과 보고서',
            author: 'asdf',
            isPrivate: true,
        },
        {
            id: 2,
            date: '2024-11-14',
            time: '10:30',
            title: '프로젝트 마감',
            important: true,
            content: '연말 프로젝트 최종 마감일\n- 산출물 제출\n- 결과보고서 작성\n- 리소스 정리',
            author: 'asdf',
            isPrivate: true,
        },
        {
            id: 3,
            date: '2024-11-14',
            time: '14:00',
            title: '프로젝트 리뷰 미팅',
            important: false,
            content: '프로젝트 최종 리뷰\n참석자: PM, 개발팀, 기획팀\n장소: 대회의실',
            author: 'asdf',
            isPrivate: true,
        },
        {
            id: 4,
            date: '2024-11-25',
            time: '18:00',
            title: '연말 회식 안내',
            important: false,
            content: '2024년 송년회\n장소: 한우랑\n회비: 3만원\n참석여부 회신 필수',
            author: 'asdf',
            isPrivate: true,
        },
    ],
    community: [
        {
            id: 1,
            title: '연간 회고록 작성 안내',
            author: '김현우',
            date: '11월 24일',
            content: '2024년 개인 회고록 작성 안내드립니다.\n양식: 첨부파일 참고\n제출기한: 11/30까지',
        },
        {
            id: 2,
            title: '사내 동호회 모집',
            author: '이지원',
            date: '11월 21일',
            content: '축구, 등산, 독서 동호회 신규 회원 모집\n신청방법: 사내 커뮤니티 게시판 댓글',
        },
        {
            id: 3,
            title: '연말 장기자랑 참가자 모집',
            author: '박서연',
            date: '11월 19일',
            content: '송년회 장기자랑 참가자 모집합니다.\n상품: 1등 상품권 30만원\n마감: 11/20',
        },
        {
            id: 4,
            title: '사내 독서모임 11월 도서 투표',
            author: '정민석',
            date: '11월 19일',
            content: '이번달 독서모임 도서 투표\n후보:\n1. 아침 그리고 저녁\n2. 파수꾼\n3. 세상의 마지막 기차역',
        },
        {
            id: 5,
            title: '연말 회식 메뉴 설문조사',
            author: '최유진',
            date: '11월 12일',
            content: '연말 회식 메뉴 선호도 조사\n1. 한식\n2. 중식\n3. 일식\n4. 양식\n투표마감: 11/15',
        },
    ],
    notices: [
        {
            id: 1,
            title: '11월 정기 휴무 안내',
            author: '관리자',
            date: '11월 1일',
            content: '11/25(토) 정기휴무\n* 연말정산 관련 문의는 이메일로 부탁드립니다.',
        },
        {
            id: 2,
            title: '연말 시스템 점검 안내',
            author: '관리자',
            date: '11월 3일',
            content: '11/30 23:00 - 12/1 04:00\n점검 대상: 전체 시스템\n담당자: 김OO (010-XXXX-XXXX)',
        },
        {
            id: 3,
            title: '2025년 연차 사용 지침 안내',
            author: '관리자',
            date: '11월 5일',
            content: '2025년 연차 사용 원칙\n- 분기별 최소 25% 사용\n- 3일 이상 연차는 2주 전 신청',
        },
        {
            id: 4,
            title: '연말정산 서류 제출 안내',
            author: '관리자',
            date: '11월 7일',
            content: '제출기한: 11/20까지\n필수서류: 의료비 영수증, 교육비 납입증명서, 기부금 영수증',
        },
        {
            id: 5,
            title: '사무실 냉난방 가동 시간 변경',
            author: '관리자',
            date: '11월 10일',
            content: '동절기 난방 가동 시간\n평일: 08:00 - 19:00\n주말: 09:00 - 17:00',
        },
    ],
    users: [
        {
            id: 1,
            username: 'asdf',
            password: 'asdf',
            name: '김미미미누',
            isAdmin: 1,
            joinDate: '2024-11-01',
        },
    ],
};
